### ISSUE TITLE
Misleading comment in Unity Style Sheet Documentation

### ISSUE THREAD

**Issue by ericdrobinson** [Unity-Technologies/UIElementsExamples#11]
The [Unity Style Sheets Reference](https://docs.google.com/document/d/1uxSIJNY6zDuyM4FO_zJ8sFpcZjy6rPslmw0kqZhycbM/edit#) is referred to by the linked [UI Elements Documentation](https://docs.google.com/document/d/1ZmtPhJqridaJuzoMJUtBlDq26uHHopdF8M1v6H9McTo/edit) in this repo. That document has the following comment:

>In the editor, path contain the extension and are relative to any “Resources” folder, similar to what [EditorGUIUtility.Load](https://docs.unity3d.com/ScriptReference/EditorGUIUtility.Load.html) accepts.

It would be far, _far_ better to specifically callout "Assets/Editor Default Resources" directly, rather than insinuate "any 'Resources' folder...". The standard "Resources" folders _are not_ searched by this API but are also far more well-known. The documentation would be much more clear if written as something like:

_In the editor, paths contain the extension and are relative to the "Assets/Editor Default Resources" folder (the same as accepted by [EditorGUIUtility.Load](https://docs.unity3d.com/ScriptReference/EditorGUIUtility.Load.html))._

For the record, the documentation is marked "View Only". I would have preferred to leave this as an inline comment, but comment functionality appears to be turned off...

**Comment by Scorr** [comment]
The docs don't seem to mention this, but a Resources folder placed in an Editor folder (Editor/Resources) is also searched by EditorGUIUtility.Load, without including it in your build. This lets you put your resources in a more relevant location instead of the project-wide "Assets/Editor Default Resources".

**Comment by ericdrobinson** [comment]
@Scorr Has that always been the case? When did the API begin to work that way? Also, is such a `Resources` folder required to be directly below the `Editor` folder or does an `Editor` folder simply have to exist in the folder's parent hierarchy?

**Comment by Antoine-Lassauzay** [comment]
Hey, thank you for this feedback. We will work on clarifying the current state of things in the documentation, and we're also working on general improvements to the way we deal with resources from USS.

**Comment by ericdrobinson** [comment]
@Antoine-Lassauzay Do you happen to know if the [`EditorGUIUtility.Load`](https://docs.unity3d.com/ScriptReference/EditorGUIUtility.Load.html) function will work with `Resources` folders found beneath an `Editor` folder hierarchy?

If so, when did this happen? Has it _always_ been this way?

**Comment by Scorr** [comment]
@ericdrobinson No idea since when or if it was always the case. Regarding if it needs to be directly below, I haven't tested but considering editor scripts work in sub-folders of an Editor folder I imagine it's the same for Resources.

Seems that the documentation here [https://docs.unity3d.com/Manual/SpecialFolders.html](https://docs.unity3d.com/Manual/SpecialFolders.html) briefly mentions it: 

> Use the EditorGUIUtility.Load function in Editor scripts to load Assets from a Resources folder within an Editor folder. These Assets can only be loaded via Editor scripts, and are stripped from builds.

**Comment by ericdrobinson** [comment]
@Scorr Thanks for pointing that out. That _*is*_ an oddity. I've asked some Unity folks for clarification and will report back if I hear anything...

**Comment by ericdrobinson** [comment]
@Scorr @Antoine-Lassauzay I heard back from an Editor-dev contact I know at Unity about this. Apparently, the `EditorGUIUtility.Load` function looks like this:

```C#
private static Object Load(string filename, Type type)
{
    Object asset = AssetDatabase.LoadAssetAtPath("Assets/Editor Default Resources/" + filename, type);
    if (asset != null)
        return asset;

    AssetBundle bundle = GetEditorAssetBundle();
    if (bundle == null)
    {
        // If in batch mode, loading any Editor UI items shouldn't be needed
        if (Application.isBatchmode)
            return null;
        throw new NullReferenceException("Failure to load editor resource asset bundle.");
    }

    asset = bundle.LoadAsset(filename, type);
    if (asset != null)
        return asset;

    // For user project defined asset paths. Used e.g when specifying icon path for a EditorWindow, with this
    // their icon no longer needs to be located in "Assets/Editor Default Resources" folder in their project.
    return AssetDatabase.LoadAssetAtPath(filename, type);
}
```
You can see that we're actually _both_ wrong. Here's how it works:

1) Check `Assets/Editor Default Resources` for the specified asset.
1) Check the built-in _Editor Asset Bundles_ for the specified asset.
1) Attempt to load the asset **from anywhere in the project**.

The _fastest_ solution is to have your custom assets within `Assets/Editor Default Resources`. The slowest solution would be to have the custom assets _anywhere else_. What's more, there is no restriction on assets being within a `Resources` folder, whether that be under an `Editor` folder or not.

The documentation, therefore, is wrong in many locations - this includes:

* [Unity Style Sheets Reference](https://docs.google.com/document/d/1uxSIJNY6zDuyM4FO_zJ8sFpcZjy6rPslmw0kqZhycbM/edit#)
* [EditorGUI.Load API Documentation](https://docs.unity3d.com/ScriptReference/EditorGUIUtility.Load.html)
* [Special Folder Names Documentation](https://docs.unity3d.com/Manual/SpecialFolders.html)

It would be very helpful to clarify this in those locations, or at least unify the suggestions. This function seems to have been expanded over time to support every possible asset location _none_ of the documentation clearly states that fact.

**Comment by Antoine-Lassauzay** [comment]
Hi, we've update the USS reference document to detail how resource paths are interpreted.
Regarding the Scripting/Manual pages, please open bugs in the "Documentation" category.

Thank you for your feedback.

**Comment by Cameron-Owen** [comment]
5 years on and this is still confusing and examples in the documentation are often wrong.

**Comment by ZayshaaCodes** [comment]
Another year on, they did nothing to fix the documentation, I've probably reported these issues a couple times now.
Please fix the documentation so it's clear how you should be loading assets for editor ui. specifically in cases of custom inspectors and property drawers. if someone at unity knows about the issue, it should not be on us to file the bug report in the right place. you're the ones getting paid, forward a link to this thread to a person paid to deal with bug reports.

To give some semblance of actually useful info here because the first half is missinfo:
it seems the best way in cases of an EditorWindow and Editor (both derive from ScriptableObject) is to assign the uxml(VisualTreeAsset) and uss(StyleSheet) asset to the script in the inspector. you will need the editor scripts filename to match the class, and the field must be public or tagged [SerializeField]

In the case of a CustomProperyDrawer... not actually sure, according to this: [https://github.com/Unity-Technologies/UIElementsExamples/blob/master/Assets/Examples/Editor/Bindings/CustomPropertyDrawerExamples.cs](CustomPropertyDrawerExamples.cs)
Unity doesnt know either cause they use `AssetDatabase.LoadAssetAtPath<VisualTreeAsset>("Assets/Examples/Editor/Bindings/custom-drawer.uxml");`
i'm sure there's some hacky solution for that too so you have a relative path from your editor folder... i havent looked for it yet.
